/*=============================================================================
  Tungsten Automation Intelligence Agent
  04_create_views.sql
  
  Creates: Analytical views in ANALYTICS schema joining RAW + REFERENCE data
  - V_DOCUMENT_PROCESSING: IDP operations with Dublin Core types
  - V_EXTRACTION_PERFORMANCE: Field extraction accuracy metrics
  - V_WORKFLOW_PERFORMANCE: Workflow metrics with APQC process mapping
  - V_INVOICE_NETWORK: e-Invoice transactions with mandate context
  - V_CUSTOMER_HEALTH: Customer engagement composite view
  - V_PLATFORM_HEALTH: Platform metrics with ITIL KPI definitions
  - V_REVENUE_METRICS: ARR and subscription analytics
=============================================================================*/

USE DATABASE TA_INTELLIGENCE;
USE WAREHOUSE TUNGSTEN_AUTOMATION_WH;
USE SCHEMA ANALYTICS;

-- =============================================================================
-- V_DOCUMENT_PROCESSING: Core IDP operations view
-- =============================================================================
CREATE OR REPLACE VIEW V_DOCUMENT_PROCESSING AS
SELECT
    J.JOB_ID,
    J.DOCUMENT_TYPE,
    J.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_FAMILY,
    J.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.INDUSTRY,
    C.SEGMENT,
    J.RECEIVED_TS,
    J.COMPLETED_TS,
    DATEDIFF('second', J.RECEIVED_TS, J.COMPLETED_TS) AS PROCESSING_TIME_SEC,
    J.PAGE_COUNT,
    J.STATUS,
    J.REGION,
    DC.DC_TYPE_LABEL AS STANDARD_DOC_TYPE,
    DC.DC_FORMAT,
    DC.DC_SUBJECT_CATEGORY,
    DATE_TRUNC('day', J.RECEIVED_TS)::DATE AS PROCESSING_DATE,
    DATE_TRUNC('week', J.RECEIVED_TS)::DATE AS PROCESSING_WEEK,
    DATE_TRUNC('month', J.RECEIVED_TS)::DATE AS PROCESSING_MONTH
FROM RAW.DOCUMENT_PROCESSING_JOBS J
LEFT JOIN RAW.PRODUCT_DIM P ON J.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN RAW.CUSTOMER_DIM C ON J.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN REFERENCE.DUBLIN_CORE_DOCUMENT_TYPES DC ON J.DOCUMENT_TYPE = DC.DC_TYPE_LABEL;

-- =============================================================================
-- V_EXTRACTION_PERFORMANCE: Extraction accuracy and manual correction metrics
-- =============================================================================
CREATE OR REPLACE VIEW V_EXTRACTION_PERFORMANCE AS
SELECT
    E.EXTRACTION_ID,
    E.JOB_ID,
    E.FIELD_NAME,
    E.CONFIDENCE_SCORE,
    E.VALIDATION_STATUS,
    E.MANUAL_CORRECTION,
    J.DOCUMENT_TYPE,
    J.PRODUCT_ID,
    P.PRODUCT_NAME,
    J.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.INDUSTRY,
    C.SEGMENT,
    J.REGION,
    CL.MODEL_VERSION,
    CL.CONFIDENCE_SCORE AS CLASSIFICATION_CONFIDENCE,
    CASE WHEN CL.PREDICTED_CLASS = CL.ACTUAL_CLASS THEN 1 ELSE 0 END AS CLASSIFICATION_CORRECT,
    DATE_TRUNC('day', J.RECEIVED_TS)::DATE AS PROCESSING_DATE,
    DATE_TRUNC('month', J.RECEIVED_TS)::DATE AS PROCESSING_MONTH
FROM RAW.EXTRACTION_RESULTS E
JOIN RAW.DOCUMENT_PROCESSING_JOBS J ON E.JOB_ID = J.JOB_ID
LEFT JOIN RAW.PRODUCT_DIM P ON J.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN RAW.CUSTOMER_DIM C ON J.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN RAW.CLASSIFICATION_EVENTS CL ON J.JOB_ID = CL.JOB_ID;

-- =============================================================================
-- V_WORKFLOW_PERFORMANCE: Workflow metrics with APQC process classification
-- =============================================================================
CREATE OR REPLACE VIEW V_WORKFLOW_PERFORMANCE AS
SELECT
    W.INSTANCE_ID,
    W.WORKFLOW_NAME,
    W.PRODUCT_ID,
    P.PRODUCT_NAME,
    W.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.INDUSTRY,
    C.SEGMENT,
    W.START_TS,
    W.END_TS,
    DATEDIFF('second', W.START_TS, W.END_TS) AS DURATION_SEC,
    W.STATUS,
    W.STEPS_COMPLETED,
    W.STEPS_TOTAL,
    CASE WHEN W.STEPS_TOTAL > 0 THEN W.STEPS_COMPLETED::FLOAT / W.STEPS_TOTAL ELSE 0 END AS COMPLETION_RATE,
    W.APQC_PROCESS_ID,
    A.PROCESS_NAME AS APQC_PROCESS_NAME,
    A.CATEGORY_CODE AS APQC_CATEGORY,
    PA.PROCESS_NAME AS APQC_PARENT_PROCESS,
    DATE_TRUNC('day', W.START_TS)::DATE AS WORKFLOW_DATE,
    DATE_TRUNC('week', W.START_TS)::DATE AS WORKFLOW_WEEK,
    DATE_TRUNC('month', W.START_TS)::DATE AS WORKFLOW_MONTH
FROM RAW.WORKFLOW_INSTANCES W
LEFT JOIN RAW.PRODUCT_DIM P ON W.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN RAW.CUSTOMER_DIM C ON W.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN REFERENCE.APQC_PROCESS_TAXONOMY A ON W.APQC_PROCESS_ID = A.PROCESS_ID
LEFT JOIN REFERENCE.APQC_PROCESS_TAXONOMY PA ON A.PARENT_ID = PA.PROCESS_ID;

-- =============================================================================
-- V_INVOICE_NETWORK: e-Invoice transactions with mandate/compliance context
-- =============================================================================
CREATE OR REPLACE VIEW V_INVOICE_NETWORK AS
SELECT
    T.TRANSACTION_ID,
    T.SENDER_ID,
    T.RECEIVER_ID,
    T.INVOICE_NUMBER,
    T.AMOUNT,
    T.CURRENCY,
    T.COUNTRY_CODE,
    T.COMPLIANCE_STANDARD,
    T.STATUS,
    T.SUBMITTED_TS,
    T.DELIVERED_TS,
    DATEDIFF('second', T.SUBMITTED_TS, T.DELIVERED_TS) AS DELIVERY_TIME_SEC,
    T.REJECTION_REASON,
    M.STANDARD_NAME AS MANDATE_NAME,
    M.MANDATORY_FLAG AS MANDATE_MANDATORY,
    M.CLEARANCE_MODEL,
    M.EFFECTIVE_DATE AS MANDATE_EFFECTIVE_DATE,
    CS.CUSTOMER_NAME AS SENDER_NAME,
    CS.INDUSTRY AS SENDER_INDUSTRY,
    CR.CUSTOMER_NAME AS RECEIVER_NAME,
    DATE_TRUNC('day', T.SUBMITTED_TS)::DATE AS TRANSACTION_DATE,
    DATE_TRUNC('week', T.SUBMITTED_TS)::DATE AS TRANSACTION_WEEK,
    DATE_TRUNC('month', T.SUBMITTED_TS)::DATE AS TRANSACTION_MONTH
FROM RAW.INVOICE_NETWORK_TRANSACTIONS T
LEFT JOIN REFERENCE.EINVOICE_MANDATE_REGISTRY M ON T.COUNTRY_CODE = M.COUNTRY_CODE
LEFT JOIN RAW.CUSTOMER_DIM CS ON T.SENDER_ID = CS.CUSTOMER_ID
LEFT JOIN RAW.CUSTOMER_DIM CR ON T.RECEIVER_ID = CR.CUSTOMER_ID;

-- =============================================================================
-- V_CUSTOMER_HEALTH: Composite customer engagement view
-- =============================================================================
CREATE OR REPLACE VIEW V_CUSTOMER_HEALTH AS
SELECT
    U.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.INDUSTRY,
    C.COUNTRY,
    C.SEGMENT,
    C.ACCOUNT_MANAGER,
    U.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_FAMILY,
    U.USAGE_DATE,
    U.DOCUMENTS_PROCESSED,
    U.PAGES_PROCESSED,
    U.API_CALLS,
    U.ACTIVE_USERS,
    S.TIER,
    S.ARR_USD,
    S.DOCUMENT_VOLUME_LIMIT,
    S.RENEWAL_DATE,
    CASE WHEN S.DOCUMENT_VOLUME_LIMIT > 0 
        THEN U.DOCUMENTS_PROCESSED::FLOAT / (S.DOCUMENT_VOLUME_LIMIT / 365.0) * 100 
        ELSE 0 
    END AS DAILY_UTILIZATION_PCT,
    IC.NAICS_CODE,
    IC.TYPICAL_DOCUMENT_TYPES,
    IC.REGULATORY_BODY
FROM RAW.CUSTOMER_USAGE_METRICS U
JOIN RAW.CUSTOMER_DIM C ON U.CUSTOMER_ID = C.CUSTOMER_ID
JOIN RAW.PRODUCT_DIM P ON U.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN RAW.CUSTOMER_SUBSCRIPTIONS S ON U.CUSTOMER_ID = S.CUSTOMER_ID AND U.PRODUCT_ID = S.PRODUCT_ID
LEFT JOIN REFERENCE.INDUSTRY_CLASSIFICATION IC ON C.INDUSTRY = IC.INDUSTRY_NAME;

-- =============================================================================
-- V_SUPPORT_METRICS: Support ticket analytics
-- =============================================================================
CREATE OR REPLACE VIEW V_SUPPORT_METRICS AS
SELECT
    T.TICKET_ID,
    T.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.INDUSTRY,
    C.SEGMENT,
    T.PRODUCT_ID,
    P.PRODUCT_NAME,
    T.SEVERITY,
    T.CATEGORY,
    T.OPENED_TS,
    T.RESOLVED_TS,
    DATEDIFF('hour', T.OPENED_TS, T.RESOLVED_TS) AS RESOLUTION_HOURS,
    T.RESOLUTION_TYPE,
    T.CSAT_SCORE,
    DATE_TRUNC('day', T.OPENED_TS)::DATE AS TICKET_DATE,
    DATE_TRUNC('month', T.OPENED_TS)::DATE AS TICKET_MONTH
FROM RAW.SUPPORT_TICKETS T
LEFT JOIN RAW.CUSTOMER_DIM C ON T.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN RAW.PRODUCT_DIM P ON T.PRODUCT_ID = P.PRODUCT_ID;

-- =============================================================================
-- V_PLATFORM_HEALTH: Platform metrics with ITIL context
-- =============================================================================
CREATE OR REPLACE VIEW V_PLATFORM_HEALTH AS
SELECT
    H.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_FAMILY,
    P.DEPLOYMENT_MODEL,
    H.REGION,
    H.METRIC_HOUR,
    H.AVAILABILITY_PCT,
    H.AVG_RESPONSE_MS,
    H.ERROR_RATE_PCT,
    H.QUEUE_DEPTH,
    DATE_TRUNC('day', H.METRIC_HOUR)::DATE AS METRIC_DATE,
    DATE_TRUNC('week', H.METRIC_HOUR)::DATE AS METRIC_WEEK,
    HOUR(H.METRIC_HOUR) AS HOUR_OF_DAY,
    CASE WHEN HOUR(H.METRIC_HOUR) BETWEEN 8 AND 18 THEN 'Business Hours' ELSE 'Off Hours' END AS TIME_CATEGORY
FROM RAW.PLATFORM_HEALTH_METRICS H
LEFT JOIN RAW.PRODUCT_DIM P ON H.PRODUCT_ID = P.PRODUCT_ID;

-- =============================================================================
-- V_REVENUE_METRICS: ARR and subscription analytics
-- =============================================================================
CREATE OR REPLACE VIEW V_REVENUE_METRICS AS
SELECT
    S.SUBSCRIPTION_ID,
    S.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.INDUSTRY,
    C.COUNTRY,
    C.SEGMENT,
    S.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_FAMILY,
    S.TIER,
    S.START_DATE,
    S.RENEWAL_DATE,
    S.ARR_USD,
    S.DOCUMENT_VOLUME_LIMIT,
    S.STATUS,
    DATEDIFF('day', CURRENT_DATE(), S.RENEWAL_DATE) AS DAYS_TO_RENEWAL,
    IC.NAICS_CODE,
    IC.REGULATORY_BODY
FROM RAW.CUSTOMER_SUBSCRIPTIONS S
JOIN RAW.CUSTOMER_DIM C ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN RAW.PRODUCT_DIM P ON S.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN REFERENCE.INDUSTRY_CLASSIFICATION IC ON C.INDUSTRY = IC.INDUSTRY_NAME;
